[package]
name = "github-action-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
dialoguer = "0.11.0"
git2 = "0.18.1"
regex = "1.10.2"
reqwest = "0.11.22"
serde_json = "1.0.108"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
